function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function navig_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".navig__list_item a[href='"+url+"']").addClass("t-active");$(".navig__list_item a[href='"+url+"/']").addClass("t-active");$(".navig__list_item a[href='"+pathname+"']").addClass("t-active");$(".navig__list_item a[href='/"+pathname+"']").addClass("t-active");$(".navig__list_item a[href='"+pathname+"/']").addClass("t-active");$(".navig__list_item a[href='/"+pathname+"/']").addClass("t-active")}
function navig_checkAnchorLinks(recid){if($(window).width()>=960){var navig_navLinks=$("#rec"+recid+" .navig__list_item a:not(.tooltipstered)[href*='#']");if(navig_navLinks.length>0){navig_catchScroll(navig_navLinks)}}}
function navig_catchScroll(navig_navLinks){var navig_clickedSectionId=null,navig_sections=new Array(),navig_sectionIdTonavigationLink={},navig_interval=100,navig_lastCall,navig_timeoutId,navig_offsetTop=$(".t270").attr("data-offset-top");if(typeof navig_offsetTop=="undefined"){navig_offsetTop=0}
navig_navLinks=$(navig_navLinks.get().reverse());navig_navLinks.each(function(){var navig_cursection=navig_getSectionByHref($(this));if(typeof navig_cursection.attr("id")!="undefined"){navig_sections.push(navig_cursection)}
navig_sectionIdTonavigationLink[navig_cursection.attr("id")]=$(this)});navig_highlightNavLinks(navig_navLinks,navig_sections,navig_sectionIdTonavigationLink,navig_clickedSectionId,navig_offsetTop);navig_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){navig_navLinks.removeClass('t-active');navig_sectionIdTonavigationLink[navig_getSectionByHref($(this)).attr("id")].addClass('t-active');navig_clickedSectionId=navig_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var navig_now=new Date().getTime();if(navig_lastCall&&navig_now<(navig_lastCall+navig_interval)){clearTimeout(navig_timeoutId);navig_timeoutId=setTimeout(function(){navig_lastCall=navig_now;navig_clickedSectionId=navig_highlightNavLinks(navig_navLinks,navig_sections,navig_sectionIdTonavigationLink,navig_clickedSectionId,navig_offsetTop)},navig_interval-(navig_now-navig_lastCall))}else{navig_lastCall=navig_now;navig_clickedSectionId=navig_highlightNavLinks(navig_navLinks,navig_sections,navig_sectionIdTonavigationLink,navig_clickedSectionId,navig_offsetTop)}})}
function navig_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function navig_highlightNavLinks(navig_navLinks,navig_sections,navig_sectionIdTonavigationLink,navig_clickedSectionId,offsetTop){var navig_scrollPosition=$(window).scrollTop(),navig_valueToReturn=navig_clickedSectionId;$(navig_sections).each(function(e){var navig_curSection=$(this),navig_sectionTop=navig_curSection.offset().top,navig_id=navig_curSection.attr('id'),navig_navLink=navig_sectionIdTonavigationLink[navig_id];if(navig_scrollPosition>=(navig_sectionTop-offsetTop)||(navig_sections[0].attr("id")==navig_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(navig_clickedSectionId==null&&!navig_navLink.hasClass('t-active')){navig_navLinks.removeClass('t-active');navig_navLink.addClass('t-active');navig_valueToReturn=null}else{if(navig_clickedSectionId!=null&&navig_id==navig_clickedSectionId){navig_valueToReturn=null}}
return!1}});return navig_valueToReturn}
function navig_setPath(){}
function navig_setWidth(recid){var window_width=$(window).width();if(window_width>980){$(".navig").each(function(){var el=$(this);var left_exist=el.find('.navig__leftcontainer').length;var left_w=el.find('.navig__leftcontainer').outerWidth(!0);var max_w=left_w;var right_exist=el.find('.navig__rightcontainer').length;var right_w=el.find('.navig__rightcontainer').outerWidth(!0);var items_align=el.attr('data-menu-items-align');if(left_w<right_w)max_w=right_w;max_w=Math.ceil(max_w);var center_w=0;el.find('.navig__centercontainer').find('li').each(function(){center_w+=$(this).outerWidth(!0)});var padd_w=40;var maincontainer_width=el.find(".navig__maincontainer").outerWidth(!0);if(maincontainer_width-max_w*2-padd_w*2>center_w+20){if(items_align=="center"||typeof items_align==="undefined"){el.find(".navig__leftside").css("min-width",max_w+"px");el.find(".navig__rightside").css("min-width",max_w+"px");el.find(".navig__list").removeClass("navig__list_hidden")}}else{el.find(".navig__leftside").css("min-width","");el.find(".navig__rightside").css("min-width","")}})}}
function navig_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".navig").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".navig").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function navig_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".navig").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function navig_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".navig").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||(typeof menushadow=="undefined"&&menushadow==!1)){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function navig_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".navig"),burger=el.find(".navig__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("navig_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}